# Generated by Django 5.0.6 on 2024-10-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['id']},
        ),
    ]
