# Generated by Django 5.1.1 on 2024-09-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_userquiz_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='session_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
