# Generated by Django 5.1.1 on 2024-09-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_useranswer_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='session_id',
        ),
    ]
