# Generated by Django 5.0.6 on 2024-09-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_useranswer_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SephoraProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField()),
                ('product_url', models.URLField()),
            ],
        ),
    ]
