# Generated by Django 5.0.6 on 2024-09-16 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_sephoraproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SephoraProduct',
        ),
    ]
